# 1. Objetivo

## Objetivo del notebook

Este notebook tiene como objetivo preparar el **dataset analítico definitivo** para su utilización en herramientas de Business Intelligence.

A diferencia de los notebooks anteriores, en esta fase no se generan nuevas variables ni se realizan análisis exploratorios. Su propósito es validar la estructura del dataset enriquecido, garantizar su consistencia y exportar un modelo analítico optimizado para su consumo en Power BI u otras herramientas de visualización.

### Problema que resuelve

Garantizar que el dataset final pueda utilizarse directamente en herramientas de Business Intelligence sin necesidad de realizar transformaciones adicionales.

### Pregunta que responde

**¿Está el dataset analítico preparado para ser consumido directamente por una herramienta de Business Intelligence?**

### Valor para el negocio

Centralizar la preparación del modelo analítico en Python mejora la trazabilidad del proyecto, reduce la complejidad del modelo en la herramienta de visualización y facilita la reutilización del dataset en distintas plataformas de Business Intelligence.

### Alcance

Este notebook incluye:

- Carga del dataset enriquecido.
- Validación de su estructura e integridad.
- Revisión del modelo analítico.
- Preparación del dataset final.
- Exportación del dataset para herramientas BI.

### Exclusiones

Este notebook no incluye:

- Nuevas transformaciones de datos.
- Creación de variables derivadas.
- Análisis estadísticos.
- Obtención de Business Insights.
- Desarrollo del dashboard.

### Dataset de entrada

`customer_features.csv`

### Dataset de salida

`customer_dashboard.csv`

In [1]:
# =============================================================================
# IMPORTACIÓN DE LIBRERÍAS
# =============================================================================

from pathlib import Path

import pandas as pd

In [2]:
# =============================================================================
# CONFIGURACIÓN DEL ENTORNO
# =============================================================================

try:
    PROJECT_ROOT = Path.cwd().resolve().parent

    DATA_PATH = PROJECT_ROOT / "data"
    PROCESSED_DATA_PATH = DATA_PATH / "processed"

    print(f"✅ Directorio raíz: {PROJECT_ROOT}")

except Exception as error:
    print(f"❌ Error al configurar el entorno: {error}")
    raise

✅ Directorio raíz: C:\Users\Lenovo\OneDrive\Documentos\Data_Projects\retail-banking-customer-intelligence

In [3]:
# =============================================================================
# VERIFICACIÓN DE RUTAS
# =============================================================================

print(f"Data: {DATA_PATH}")
print(f"Processed: {PROCESSED_DATA_PATH}")

Data: C:\Users\Lenovo\OneDrive\Documentos\Data_Projects\retail-banking-customer-intelligence\data
Processed: C:\Users\Lenovo\OneDrive\Documentos\Data_Projects\retail-banking-customer-intelligence\data\processed

# 4. Carga del dataset enriquecido

## Objetivo

Cargar el dataset enriquecido generado en el Notebook 03 y verificar que la importación se realiza correctamente.

Este dataset constituye el punto de partida para la validación y preparación del modelo analítico definitivo que será utilizado por herramientas de Business Intelligence.

In [4]:
# =============================================================================
# CARGA DEL DATASET ENRIQUECIDO
# =============================================================================

INPUT_PATH = PROCESSED_DATA_PATH / "customer_features.csv"

try:
    customer_dashboard_df = pd.read_csv(INPUT_PATH)

    print("✅ Dataset cargado correctamente.")

except Exception as error:
    print(f"❌ Error al cargar el dataset: {error}")
    raise

✅ Dataset cargado correctamente.

In [5]:
# =============================================================================
# VERIFICACIÓN DE LA CARGA
# =============================================================================

print(f"Filas: {customer_dashboard_df.shape[0]}")
print(f"Columnas: {customer_dashboard_df.shape[1]}")

display(customer_dashboard_df.head())

Filas: 50000
Columnas: 15

,customer_id,credit_score,total_accounts,total_balance,total_cards,total_loans,total_loan_amount,total_transactions,total_transaction_amount,total_products,avg_transaction_amount,avg_loan_amount,engagement_level,multi_product,balance_level
0,CUS000MKX5RHTAP,827,1,151677.32,4,0,0.0,6,26890.44,5,4481.740000,0.0,Medium,Yes,Medium
1,CUS002V4AVJO5UQ,510,1,178960.28,1,0,0.0,16,76937.17,2,4808.573125,0.0,Low,Yes,Medium
2,CUS004THQ8NDQW3,636,1,131026.41,1,1,204044.4,9,33025.48,3,3669.497778,204044.4,Medium,Yes,Medium
3,CUS007GCM2J726A,492,2,81689.89,2,0,0.0,20,107590.15,4,5379.507500,0.0,Medium,Yes,Medium
4,CUS00AO13A3Q5FO,686,2,189090.18,1,1,61678.8,26,120446.58,4,4632.560769,61678.8,Medium,Yes,Medium

# 5. Validación del modelo analítico

## Objetivo

Verificar que el modelo analítico mantiene su integridad estructural y cumple los requisitos necesarios para ser utilizado directamente en herramientas de Business Intelligence.

Durante esta fase no se realizarán transformaciones sobre los datos. Únicamente se comprobará la calidad del modelo analítico antes de su exportación.

In [6]:
# =============================================================================
# VALIDACIÓN DEL MODELO ANALÍTICO
# =============================================================================

print(f"Filas: {customer_dashboard_df.shape[0]}")
print(f"Columnas: {customer_dashboard_df.shape[1]}")

print("\nValores nulos")
display(customer_dashboard_df.isna().sum())

duplicates = customer_dashboard_df.duplicated(
    subset="customer_id"
).sum()

print(f"\nClientes duplicados: {duplicates}")

print("\nTipos de datos")
customer_dashboard_df.info()

Filas: 50000
Columnas: 15

Valores nulos

customer_id                 0
credit_score                0
total_accounts              0
total_balance               0
total_cards                 0
total_loans                 0
total_loan_amount           0
total_transactions          0
total_transaction_amount    0
total_products              0
avg_transaction_amount      0
avg_loan_amount             0
engagement_level            0
multi_product               0
balance_level               0
dtype: int64

Clientes duplicados: 0

Tipos de datos
<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               50000 non-null  str
 1   credit_score              50000 non-null  int64
 2   total_accounts            50000 non-null  int64
 3   total_balance             50000 non-null  float64
 4   total_cards               50000 non-null  int64
 5   total_loans               50000 non-null  int64
 6   total_loan_amount         50000 non-null  float64
 7   total_transactions        50000 non-null  int64
 8   total_transaction_amount  50000 non-null  float64
 9   total_products            50000 non-null  int64
 10  avg_transaction_amount    50000 non-null  float64
 11  avg_loan_amount           50000 non-null  float64
 12  engagement_level          50000 non-null  str
 13  multi_product             50000 non-null  str
 14  balance_level             50000 non-null  str
dtypes: float64(5), int64(6), str(4)
memory usage: 5.7 MB

### Análisis e interpretación

La validación confirma que el modelo analítico mantiene su estructura original tras el proceso de preparación realizado en los notebooks anteriores.

El dataset contiene 50.000 clientes, 15 variables, no presenta valores nulos ni registros duplicados y conserva los tipos de datos esperados.

En consecuencia, el modelo queda preparado para su utilización en herramientas de Business Intelligence.

# 6. Modelo analítico

## Objetivo

Documentar la estructura del modelo analítico definitivo que será utilizado por herramientas de Business Intelligence.

El modelo mantiene la estructura definida durante el desarrollo del proyecto y no requiere modificaciones adicionales antes de su exportación.

| Variable | Tipo | Origen |
|-----------|------|---------|
| customer_id | Identificador | Original |
| credit_score | Numérica | Original |
| total_accounts | Numérica | SQL |
| total_balance | Numérica | SQL |
| total_cards | Numérica | SQL |
| total_loans | Numérica | SQL |
| total_loan_amount | Numérica | SQL |
| total_transactions | Numérica | SQL |
| total_transaction_amount | Numérica | SQL |
| total_products | Derivada | Notebook 03 |
| avg_transaction_amount | Derivada | Notebook 03 |
| avg_loan_amount | Derivada | Notebook 03 |
| engagement_level | Categórica | Notebook 03 |
| multi_product | Categórica | Notebook 03 |
| balance_level | Categórica | Notebook 03 |

### Estado del modelo

La revisión final confirma que la estructura del modelo analítico es consistente con el diseño aprobado para el proyecto.

No ha sido necesario modificar el orden ni la nomenclatura de las variables, ya que la organización actual facilita su interpretación y mantiene la trazabilidad respecto a las fases anteriores del proyecto.

In [7]:
customer_dashboard_df[
    ["total_balance",
     "total_transaction_amount",
     "avg_transaction_amount"]
].head()

   total_balance  total_transaction_amount  avg_transaction_amount
0      151677.32                  26890.44             4481.740000
1      178960.28                  76937.17             4808.573125
2      131026.41                  33025.48             3669.497778
3       81689.89                 107590.15             5379.507500
4      189090.18                 120446.58             4632.560769

In [8]:
customer_dashboard_df.dtypes

customer_id                     str
credit_score                  int64
total_accounts                int64
total_balance               float64
total_cards                   int64
total_loans                   int64
total_loan_amount           float64
total_transactions            int64
total_transaction_amount    float64
total_products                int64
avg_transaction_amount      float64
avg_loan_amount             float64
engagement_level                str
multi_product                   str
balance_level                   str
dtype: object

In [9]:
# =============================================================================
# EXPORTACIÓN DEL DATASET PARA BUSINESS INTELLIGENCE
# =============================================================================

OUTPUT_PATH = PROCESSED_DATA_PATH / "customer_dashboard.csv"

try:
    customer_dashboard_df.to_csv(
        OUTPUT_PATH,
        index=False
    )

    print(f"✅  Dataset para Business Intelligence exportado correctamente:\n{OUTPUT_PATH}")

except Exception as error:
    print(f"❌ Error durante la exportación: {error}")
    raise

✅  Dataset para Business Intelligence exportado correctamente:
C:\Users\Lenovo\OneDrive\Documentos\Data_Projects\retail-banking-customer-intelligence\data\processed\customer_dashboard.csv

# 7. Conclusiones

El modelo analítico ha sido validado y preparado para su utilización en herramientas de Business Intelligence.

La revisión final confirma la integridad estructural del dataset, la ausencia de valores nulos y registros duplicados, y la correcta definición de las variables incorporadas durante las fases anteriores del proyecto.

El resultado de este notebook es un dataset analítico reutilizable, preparado para alimentar herramientas de Business Intelligence sin necesidad de transformaciones adicionales.

Con ello finaliza la fase Python del proyecto, quedando el modelo listo para el desarrollo del dashboard y la comunicación de resultados.